= Fraud Detection with Apache Flink

[[overview]]
== Overview
Fraud Detection engine is to consume a stream of financial transactions and evaluate them against a set of rules. Any transaction that violates a rule is flagged as a potential fraud. The engine is implemented using Apache Flink and is deployed as a standalone application. The engine is integrated with a web application that allows users to configure rules and view transactions that are flagged as potential fraud.


[[architecture]]
== Module Architecture
Fraud detection demo system consists of three main components:

- fraud-detection-common: Common library for the Fraud Detection application
- fraud-detection-flink-job: Fraud Detection application (Apache Flink)
- fraud-detection-simulator: Fraud Detection simulator web application, which is used to generate transactions and send them to the flink job

[[requirements]]
== Requirements
Before you can build this project, you must install JDK on your machine. You can install JDK by https://sdkman.io/install[SDK Man]. e.g.
```bash
sdk install java 11.0.20-tem
```
NOTE: Java compatability: JDK 11

[[dependencies]]
== Dependencies
- flink 1.15.4
- spring-boot 2.7.1

[[build]]
== Build
Run the following command to build the project:

```
./mvnw clean verify
```

[[run]]
== Run
This project contains multiple sub-modules.

Run fraud-detection-flink-job module with main() method of:
`com.luixtech.frauddetection.flinkjob.FlinkJobLauncher`

Access Flink Web UI with URL:
http://localhost:8081[http://localhost:8081]


Run fraud-detection-simulator module with main() method of:
`com.luixtech.frauddetection.simulator.SimulatorLauncher`

Access swagger with URL:
http://localhost:5656[http://localhost:5656]

Access H2 Console with URL:
http://localhost:5656/h2-console[http://localhost:5656/h2-console]

|===
|Setting |Value

|Driver Class
|org.h2.Driver

|JDBC URL
|jdbc:h2:mem:simulator

|Username
|sa

|Password
|

|===


[[InstallDocker]]
== Install Docker
```
curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun
```

[[UsingDocker]]
== Using Docker to simplify development (optional)
To start zookeeper and Kafka in a docker container, run:

```
docker-compose -f docker/all.yml up -d
```

To stop it and remove the container, run:

```
docker-compose -f docker/all.yml down
```

[[VMOptions]]
== VM Options
Add below Key/Value pair to env variable of rancher.
```
key: JAVA_OPTS
value: -Dspring.profiles.active=XXX
```

[[troubleshooting]]
== Troubleshooting
Error:
```
./mvnw: Permission denied
```

Solution:
```
chmod +x mvnw
git update-index --chmod=+x mvnw
```

[[contacts]]
== Contacts
- Email: louis@luixtech.com

[[references]]
== References
https://github.com/afedulov/fraud-detection-demo/tree/with-1.15[Fraud detection demo code repository]

https://mp.weixin.qq.com/s?__biz=MzIxMTE0ODU5NQ==&mid=2650244230&idx=1&sn=0e84cb5448542566a852232b7ebf21ae&chksm=8f5aeedab82d67ccc5c70acc0bdcbdd564eda2671a32e710a84f0154ea39d9377bdfb66840ed&cur_album_id=1561681981896179713&scene=189#wechat_redirect[基于 Flink 的动态欺诈检测系统（上）]

https://flink.apache.org/2020/01/15/advanced-flink-application-patterns-vol.1-case-study-of-a-fraud-detection-system/[Advanced Flink Application Patterns Vol.1: Case Study of a Fraud Detection System]
