= Fraud Detection Demo with Apache Flink


[[websites]]
== Websites
http://10.167.76.222:8088[Test environment]


[[overview]]
== Overview
TSAP [Telematics Service Provider Stream Analysis Platform] is used to analyze the historical and real-time data and detect security threats for auto on server side.

[[requirements]]
== Requirements
Before you can build this project, you must install JDK on your machine. You can install JDK by https://sdkman.io/install[SDK Man]. e.g.
```bash
sdk install java 17.0.6-tem
```
NOTE: Java compatability: JDK 17 above

[[dependencies]]
== Dependencies
- spring-boot 2.6.11
- spring-cloud-alibaba 2021.0.4.0

[[build]]
== Build
Run the following command to build the project:

```
./mvnw clean verify
```

[[run]]
== Run
This project contains multiple sub-modules.

Run TSAP API app server:

```bash
java -jar tsap-api/tsap-api-app/target/*.jar
```

Then navigate to http://localhost:8088[http://localhost:8088] in your browser.

[[CIScript]]
== CI Script
Build the docker image and push it to Harbor registry with the link:push-docker-image.sh[shell script]:
```
include::push-docker-image.sh[]
```

[[InstallDocker]]
== Install Docker
```
curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun
```

[[VMOptions]]
== VM Options
Add below Key/Value pair to env variable of rancher.
```
key: JAVA_OPTS
value: -Dspring.profiles.active=XXX
```

[[ArthasUsages]]
== Arthas Usages
=== Run Arthas
```
./arthas-run.sh
```

=== Invoke method
First get the spring context object by tt(time tunnel) command
```
tt -t org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter invokeHandlerMethod
```
Output:
```
 INDEX        TIMESTAMP                        COST(ms)        IS-RET       IS-EXP       OBJECT                  CLASS                                            METHOD

--------------------------------------------------------------------------------------------

 1000         2023-01-30 11:50:44              4.825545        true         false        0x15c8b75c              RequestMappingHandlerAdapter                     invokeHandlerMethod
```
We can get the index value(1000). Then we can get any spring bean objects and invoke any methods.
```
tt -i 1000 -w 'target.getApplicationContext().getBean("threatSeverityRepository").findAll()'
```
Output:
```
@ArrayList[
@ThreatSeverity[ThreatSeverity(super=AbstractAuditableDomain(id=63be1662832439552abfd384, createdBy=louis, createdTime=2023-01-11T01:52:34.600Z, modifiedBy=louis, modifiedTime=2023-01-11T01:52:34.600Z), seqNum=1, code=critical, name=严重, score=0, enabled=true)]
]
```
Invoke another method
```
tt -i 1000 -w 'target.getApplicationContext().getBean("threatSeverityRepository").findById("63be1662832439552abfd384")'
```

=== Monitor the execution time, arguments and return value of method
Command:
```
watch cn.com.bydauto.tsap.apiapp.controller.ThreatTypeController findAllCodes
```
We can get the output after invocation:
```
Affect(class count: 2 , method count: 2) cost in 52 ms, listenerId: 3
method=cn.com.bydauto.tsap.apiapp.controller.ThreatTypeController.findAllCodes location=AtExit
ts=2023-01-30 11:42:56; [cost=0.657476ms] result=@ArrayList[
    @Object[][isEmpty=true;size=0],
    @ThreatTypeController[cn.com.bydauto.tsap.apiapp.controller.ThreatTypeController@10f192d8],
    @Result[Result(code=TSAPS0000, message=处理成功, result=[vlan-up-down-traffic, vehicle-equipment-connection, door-switch, ota-upgrade])],
]
```


[[troubleshooting]]
== Troubleshooting
Error:
```
./mvnw: Permission denied
```

Solution:
```
chmod +x mvnw
git update-index --chmod=+x mvnw
```

[[contacts]]
== Contacts
- Email: liu.yao24@byd.com

[[references]]
== References
https://blog.51cto.com/u_15147537/5969322[AsciiDoc使用手册]

https://blog.csdn.net/qq_42971035/article/details/126904015[SpringCloud的nacos多项目、多环境的命名空间和分组配置]

https://github.com/alibaba/arthas/issues/482[Alibaba Arthas实践--获取到Spring Context]
